import mongoose from 'mongoose';

const slotSchema = new mongoose.Schema({
  day: { type: String, enum: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] },
  startTime: { type: String, required: true }, // e.g., '09:00'
  endTime: { type: String, required: true },
  subject: { type: String },
  teacher: { type: String },
  location: { type: String },
  break: { type: Boolean, default: false }
});

const subjectSchema = new mongoose.Schema({
  name: { type: String, required: true },
  lecturesPerDay: { type: Number, default: 1, min: 1, max: 5 },
  teacher: { type: String }
});

const breakTimeSchema = new mongoose.Schema({
  startTime: { type: String, required: true },
  endTime: { type: String, required: true }
});

const schoolHoursSchema = new mongoose.Schema({
  startTime: { type: String, default: '08:00' },
  endTime: { type: String, default: '15:00' },
  slotDuration: { type: Number, default: 45 } // in minutes
});

const timetableSchema = new mongoose.Schema({
  class: { type: String, required: true }, // e.g., '10th Grade'
  section: { type: String },
  slots: [slotSchema],
  subjects: [subjectSchema],
  breakTimes: [breakTimeSchema],
  schoolHours: schoolHoursSchema,
  generatedByAI: { type: Boolean, default: false }, // Flag for AI-generated
  autoGenerated: { type: Boolean, default: false }, // Flag for auto-generated
  conflicts: [{ type: String }], // Array of conflict descriptions
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now }
});

// Method to check for conflicts (basic example)
timetableSchema.methods.hasConflicts = function() {
  // Logic to detect overlapping slots, etc.
  return this.conflicts.length > 0;
};

export default mongoose.model('Timetable', timetableSchema);
